### ISSUE TITLE
Insert <link rel=preload> tags into html on production

### ISSUE THREAD

**Issue by v0idifier** [jakedeichert/svelvet#22]
Even when using http/2, a site using snowpack/svelvet can take some time to load because it has to get the whole dependency slowly. This can be prevented using [`<link rel=reload>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content) tags.

**Comment by v0idifier** [comment]
I'm trying to implement this but I'm struggling with Typescript.

**Comment by jakedeichert** [comment]
Hmmm, could you explain what the issue is here? I understand link preload, but in my opinion, this is not part of svelvet's job. We should only be copying html files to dist and not manipulate them in any way. If i'm misunderstanding, let me know!

As for who should add link preload, i think that should be on the user to do post-build.

**Comment by jakedeichert** [comment]
> We should only be copying html files to dist and not manipulate them in any way.

To explain further, this is part of the simplicity svelvet is trying to strive for :). Just a simple src>dist watcher which optimizes the js output with the help of snowpack and terser. Letting users control their html files is ideal... definitely do not want to become another complex bundler with configuration.

**Comment by v0idifier** [comment]
okay. no, it makes sense. i was thinking that maybe it could of been done inside of svelvet because it knows the name of the `.js` files generated, but it makes sense.
