### ISSUE TITLE
[question] building html files as a fallback

### ISSUE THREAD

**Issue by MarcCoet** [jakedeichert/svelvet#31]
Svelvet is awesome. In a perfect world everybody would just use a recent browser and DX like this would be the norm.
Until then I truly believe in progressive enhancement in the sense that [Andy Bell describes it](https://hankchizljaw.com/wrote/the-p-in-progressive-enhancement-stands-for-pragmatism/). We don't need to support legacy browser with the exact same user experience that we provide to recent ones.

So why don't we create html files for every route that renders some?
If the browser does not support web modules or has JS deactivated, html will still be available. Plus, we get bonus points for SEO.

A quick test using the [Server-side component API](https://svelte.dev/docs#Server-side_component_API) was pretty convincing.

There is a lot I don't know about SSR, rehydration, etc so that is a very naive interrogation. I hope someone smarter can provide relevant feedback about this idea.

Cheers

**Comment by jakedeichert** [comment]
I've been thinking about static site prerendering A LOT for a while now but i'm not sure it fits in with svelvet's goals of being just a src/dist esm compiler.

For another svelte project i work on, i've been successfully using headless chrome to prerender all pages to html files that rehydrate on page load. It's like SSR but without the server and works very well.

At this point, it seems like prerendering should be a step the user decides to take after building with svelvet. There's many ways to prerender and a lot of considerations to take. Another tool could easily thrive just doing this aspect alone 😅 

With that said, I might be experimenting with prerendering and static tree elimination over the next few weeks when I have time. It's a problem i'm very interested in but also very experimental and I don't think it'll find its way into svelvet, at least not anytime soon.

**Comment by PKlknr** [comment]
Svelvet is amazing! I had similar ideas about prerendering when I tried it out, and hacked up a little POC to see if it works: It seems so:)

There's this interesting [PR](https://github.com/sveltejs/svelte/pull/4309) on svelte that allows one to hydrate on {target: document} - that makes it possible to prerender and hydrate components that represent the full html-document: https://github.com/PKlknr/svatic/blob/master/example/hydrate/src/Index.svelte

This removes the need for an html-file that's just a wrapper, and makes it possible to prerender without serving and crawling.

The current POC is at https://github.com/PKlknr/svatic, if you're interested.

@jakedeichert Would you consider providing an API so I can depend on svelvet? I think what it boils down to is either the ability to disable watch mode, or having a hook inside watch mode to prerender. But I need to play with it some more.

**Comment by MarcCoet** [comment]
Great! Looks like the idea is in the air! :)
@jakedeichert I hear you about the purpose of this lib. And it is great to read you are interested in prerendering. Maybe adding an API is the way to go then?
@PKlknr I will take a look at svatic and try it as soon as I can. Thanks a lot for the input.
As a related note: I have been experimenting with [ssg](https://github.com/sw-yx/ssg) as well, which is a static site generator for svelte. It is using a slightly modified version of Sapper at the moment but the idea is to get rid of it at some point. (@sw-yx, you might be interested to read this)

...so just taking a shot here... would you all 3 like to share your vision for a svelte static site generator and see if a collaboration might be a good idea?

**Comment by vipero07** [comment]
There is an existing svelte static site generator that is managed by the svelte team. [Sapper Export](https://sapper.svelte.dev/docs#Exporting) will make a static svelte site as you guys are describing. It generates HTML, CSS and JS files when using the export feature. Allowing you to use github pages and the like for a static site. Of course it has limitations with regards to sessions / authentication, but all static sites would.

**Comment by jakedeichert** [comment]
@PKlknr thanks!

> This removes the need for an html-file that's just a wrapper, and makes it possible to prerender without serving and crawling.

Interesting. I haven't tried it yet, but i think [jsdom](https://github.com/jsdom/jsdom) could also be used instead of crawling with headless chrome. I personally don't mind having an index html wrapper, but i can see how that svelte PR could make things easier for sure! 

> Would you consider providing an API so I can depend on svelvet? I think what it boils down to is either the ability to disable watch mode, or having a hook inside watch mode to prerender. But I need to play with it some more.

Exposing an api for svelvet will require some work but could make sense for the future. It's mostly just a file watcher though... I glued together a few libs which are the core pieces here. I don't have  a timeline on exposing an api right now, but if you take a look at the [index.ts](https://github.com/jakedeichert/svelvet/blob/master/src/index.ts) maybe you could just copy/paste it to your project for experimentation? I have a feeling that you may need a tighter integration to svelte's compiler than what svelvet would allow via an api anyway.


---

> ...so just taking a shot here... would you all 3 like to share your vision for a svelte static site generator and see if a collaboration might be a good idea?

@MarcCoet so **swyx** and i actually chatted a bit on twitter about this a few days ago :)
https://twitter.com/jakedeichert/status/1223364182474706945
https://twitter.com/jakedeichert/status/1223366435809964032
https://twitter.com/jakedeichert/status/1223373889625042944

The last tweet sums up my idea:

> I agree it requires a higher level build tool. However, if we're talking pure esm modules (svelvet output), no bundling, then it's a matter of removing the root app script tag and injecting dynamic script tags during the prerender step. (this was my naive starter plan)

I have the whole design in my head.. i just need to draw it on paper and maybe write a blog post. I'm just waiting for a day to hack on it :). If it works out, this means all static esm files will not be loaded at runtime, only files that are used within dynamic trees.

I imagine the post being titled "Making svelte _literally_ disappear" 😂 

---

@vipero07 yeah, i've seen sapper. The problem is it still sends down all js to the browser on page load and rehydrates. I want something that only rehydrates when needed (dynamic, interactive ui).

**Comment by jakedeichert** [comment]
Closing this issue as it's unlikely for svelvet to add ssg/prerendering right now. Existing tools do a much better job. 

I will leave this here though... it's my simple headless chrome setup.

#### prerender.config.js

```js
module.exports = {
    // The website url to load
    url: 'http://localhost:8080', // start serve or servor on this port in another terminal
    // Where to save the files to
    output: 'dist',
    // All pages to save (I haven't automated crawling. Manually adding here works for me)
    pages: [
        {
            path: '/',
        },
        {
            path: '/faq',
        },
        {
            path: '/privacy-policy',
        },
        {
            // Netlify looks for 404.html
            path: '/404',
            output: '404.html',
        },
    ],
};
```

#### prerender.js
```js
const fs = require('fs').promises;
const path = require('path');
const puppeteer = require('puppeteer');
const config = require('./prerender.config.js');

(async () => {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    // Set a global variable so the app can understand it's in prerender mode
    page.evaluateOnNewDocument(() => {
        window.__PRERENDER_MODE__ = true;
    });

    // Grab content of every page
    for (const p of config.pages) {
        const url = `${config.url}${p.path}`;
        await page.goto(url);
        p.content = await page.content();
    }

    // Save each page
    await Promise.all(
        config.pages.map(async p => {
            const fileName = p.output || path.join(p.path, 'index.html');
            const outputPath = path.join(config.output, fileName);
            await makeDir(outputPath);
            return fs.writeFile(outputPath, p.content);
        })
    );

    await browser.close();
})();

async function makeDir(outputPath) {
    await fs.mkdir(path.dirname(outputPath), { recursive: true });
}
```

**Comment by sw-yx** [comment]
yea sapper has a static export mode but the deeper you dive into it the more you realize it just isnt great as a ssg tool. hence ssg.

**Comment by MarcCoet** [comment]
Thanks for your work @jakedeichert .
> I imagine the post being titled "Making svelte literally disappear" 😂

Haha, please do post the link here when you get a chance to write it. :)

I am wondering why you are not using the svelte api to compile to html instead of headless chrome. The other day I tried fiddling a little bit with svelvet and I was able to output html files along with the JS modules pretty easily. I still have problems with hydration (either a bug or something undocumented I think) but IMO it seems cleaner...

**Comment by PKlknr** [comment]
Thanks @jakedeichert - picking your index.ts is exactly what I did;)

I'm totally open for collaboration, @MarcCoet  - I've updated the [readme](https://github.com/PKlknr/svatic) (and the code quit a bit). I think there's an intersection with svelvet and possibly ssg. For example, I've got partial builds and picking up new deps working (albeit in an embarrassingly hacky way).

**Comment by jakedeichert** [comment]
> I am wondering why you are not using the svelte api to compile to html instead of headless chrome. The other day I tried fiddling a little bit with svelvet and I was able to output html files along with the JS modules pretty easily.

Two reasons I won't be able to use svelte's SSR rendering:

1. My static tree elimination idea depends on figuring things out at _runtime_ during a prerendering phase. I have a PoC that works with headless chrome right now, but I was thinking about testing out jsdom to see if that's _enough_ of a runtime. 

2. This PoC of mine actually doesn't integrate directly with svelvet nor with svelte's compiler. The prerenderer i'm making could work with any esm-outputted svelte project. It just happens to pair well with svelvet as a post-build phase due to its esm output. If I made the prerenderer depend on svelte's SSR api, then this project would need to be integrated at the bundler level which is too limiting IMO. My idea here is that you build your website with svelte, compile with svelvet, and optionally prerender to static html files after that if desired.



---
> I'm totally open for collaboration, @MarcCoet - I've updated the readme (and the code quit a bit). I think there's an intersection with svelvet and possibly ssg. For example, I've got partial builds and picking up new deps working (albeit in an embarrassingly hacky way).

Cool! After I release my prerenderer and blog post explaining how it works, it might be possible for you to integrate my static tree elimination idea (only hydrate interactive parts of the static site) into your SSG. Up to you if it fits in with that project or not :)

**Comment by MarcCoet** [comment]
Has anyone made progress?
I have been ill for 2 weeks and finally have got a very basic [demo](https://m4rrc0.netlify.com/) made of 95% of svelvet.
I have got concrete suggestions to be able to use svelvet as the basis for a static site builder. I would only need a few small changes to the code base for now.
- exporting individual functions from `index.ts` so I could use svelvet as a library and not a cli and easily add steps to my own `initialBuild` function and still benefit from the continuous efforts your are making here on the long run.
- passing more arguments to the `compile` function: the svelte compile options and the output directory (as also discussed in #50)

For now, my process is to call the `compile` function [a second time](https://github.com/MarcCoet/m4rrco-from-scratch/blob/master/libs/build/index.esm.js#L278) to compile for SSR in another folder. Then I [generate html files](https://github.com/MarcCoet/m4rrco-from-scratch/blob/master/libs/build/index.esm.js#L104) (for all components for the moment) and place them in the dist folder alongside svelvet's normal JS files.

Would you be open to integrate these changes @jakedeichert ?

Alternatively, we could of course create an API to be able to customize the `initialBuild` function's steps. But that is more work and I totally understand that may not be the goal of this library.

**Comment by jakedeichert** [comment]
> Has anyone made progress?

I've had a super busy month and didn't get around to posting my partial-hydrating prerenderer idea. I did [work on it](https://twitter.com/jakedeichert/status/1225282697897160704) though and this is what I plan on releasing in the next month or two. 

Here's a glimpse of how you mark a component tree that you want to hydrate  after your static page has loaded. This eliminates all static trees that don't need to rerender and thus makes your client bundles much lighter. I'm really excited to get back to this.. but just too many things going on right now 😓 

![EQGbwq7WoAA_Gex](https://user-images.githubusercontent.com/1631044/75735867-b4386c80-5cc9-11ea-93f0-6b594f54e803.jpg)


> Would you be open to integrate these changes @jakedeichert ?

Since you copied the svelvet source, is there really a need for me to expose an api? :)

I think if you depended on svelvet, it will actually slow down your own experimentation. Svelvet is a really young project and I think exposing an api at this point will just be a maintenance burden I can't really take on right now. Being pre-1.0.0, I'm able to change anything fast without worrying about breaking dependents, since it's currently just a cli-only tool.

Maintaining your own fork/copy of svelvet within your static site generator makes a lot of sense to me. There's a chance one of svelvet's functions may not interoperate with your project one day and then you'll be stuck waiting on svelvet to implement or not implement certain features.

Anyway, I'm excited to see where you take your project :)

**Comment by MarcCoet** [comment]
Alright! Let's keep each other posted when things mature.
Exciting times! Exciting times!! ;)

**Comment by jakedeichert** [comment]
@MarcCoet I've got the v1 proof of concept up here: https://github.com/jakedeichert/svelte-partial-hydrating-prerenderer

Note that the README is not finished. I want to explain the "why" before I share this repo more widely on twitter... so I'm keeping it pretty quiet for now.

If you want to discuss more about prerendering, please open as many issues as you want over on that repo :)

**Comment by MarcCoet** [comment]
Awesome. Thanks @jakedeichert . I'll have a look as soon as I can clear up some time in my schedule. :)

**Comment by sw-yx** [comment]
i like how there are 3 ongoing attempts at this :) hopefully one of us gets something out soon.

**Comment by sw-yx** [comment]
another attempt https://shocky.now.sh/

**Comment by jimafisk** [comment]
Thanks for all the knowledge sharing! I'm making an attempt at something similar here: https://github.com/plentico/plenti
