### ISSUE TITLE
Support Environment Variables

### ISSUE THREAD

**Issue by JustinVoitel** [jakedeichert/svelvet#54]
What is the recommended way in bringing envs into the project ?
First I tried importing dotenv into App.svelte, but that resulted into an error(fs not found). Then I tried adding them in the snowpack config using @rollup/plugin-replace, which did nothing. Is there even a possibility ?

**Comment by jakedeichert** [comment]
So if you're looking for some way to get env variables bundled with your code, that's not part of the svelvet's goals. 

> First I tried importing dotenv into App.svelte, but that resulted into an error(fs not found). Then I tried adding them in the snowpack config using @rollup/plugin-replace, which did nothing

None of node's APIs will be available because your svelte files are not being ran through a bundler like webpack/rollup.

The short answer is, you likely will need to use a more complex bundler like webpack/rollup and not svelvet. Svelvet strives to be just a src > dist compiler for svelte and nothing more :). This inherently comes with constraints like no environment variables and no custom extension imports. 

The longer answer is give this a read: https://immutablewebapps.org/
Based on this article, I've personally started injecting `window.env` scripts into my main `index.html`. Then, all scripts just reference `window.env.ENV_VAR` instead.

Example `index.html`:

```html
<script>
window.env = {
    API: 'https://api.example.com',
    GA: 'UA-126263119-1'
}
</script>
<!-- then load your main App.js script after -->
```

---

Another alternative is that you can probably find or write a custom [svelte preprocessor](https://svelte.dev/docs#svelte_preprocess) that finds all env var references at compile time and then swaps them with their hard coded values. Svelvet [just released support](https://github.com/jakedeichert/svelvet/issues/24#issuecomment-590168558) for loading preprocessors :). Note that this wouldn't run on your normal `.js` files, so it's not really a full solution.

**Comment by jakedeichert** [comment]
@JustinVoitel actually, you could also use this [babel env var plugin](https://babeljs.io/docs/en/babel-plugin-transform-inline-environment-variables).

Just add a `babel.config.js` file to your project. Check out the example [here](https://github.com/jakedeichert/svelvet/tree/master/tests/snapshot-babel-override).
