### ISSUE TITLE
cannot import .svelte files when using TypeScript preprocessor

### ISSUE THREAD

**Issue by mvolkmann** [jakedeichert/svelvet#77]
See the simple example at https://github.com/mvolkmann/svelvet-with-typescript.
src/App.svelte contains this line which doesn't work:

```js
import DateDisplay from './DateDisplay';
```

Even with this line commented out (as it is currently) I get this error:
no such file or directory, open '.../svelvet-with-typescript/dist/web_modules/import-map.json'

**Comment by mvolkmann** [comment]
Could it be that the way imports are mapped to relative file paths in the generated import-map.json file does not work when using TypeScript as a preprocessor because that runs before the import-map.json file gets created?

**Comment by jakedeichert** [comment]
Hmmm, this probably isn't working because the `transpileOnly` option is not in your config. In this [preprocessor+typescript test/example](https://github.com/jakedeichert/svelvet/blob/c3b271a649ec3e9ecd2d54a518ee347cc7948c01/tests/snapshot-preprocessors/src/App.svelte), it works because it's not truly running all the code through typescript's compiler... just removing type info and syntax.

Not sure what the answer is here since I don't use ts with svelte. It'll require some investigation 👍

**Comment by jakedeichert** [comment]
Your [babel.config.js](https://github.com/mvolkmann/svelvet-with-typescript/blob/ac98ef7ac8e83c45c7f17b8402e421edd9fb4fe0/babel.config.js) looks like a version from an old release/example.

See the new one [here](https://github.com/jakedeichert/svelvet/blob/c3b271a649ec3e9ecd2d54a518ee347cc7948c01/tests/snapshot-babel-override/babel.config.js).

**Comment by jakedeichert** [comment]
Once you get that babel issue fixed up, that should solve the current issue you described.

The next problem is this... note the console:

<img width="1231" alt="Screen Shot 2020-04-09 at 9 57 11 PM" src="https://user-images.githubusercontent.com/1631044/78955371-18123a00-7aad-11ea-8340-bc3e42734359.png">


The svelte-preprocess typescript compilation is having problems with the import statement (because it's not .svelte) and the reactive variable `time`. These are both highly likely to be on their side since it's being thrown by the preprocessor's typescript compiler. Not much I can do here.

Honestly, the typescript and svelte story is really painful right now and I don't have time to support that with svelvet. The preprocessor support + test is there as an example for people who wanted that ability and it can be useful for things _other than_ typescript (sass, pug, etc...).

Finally, when svelte finally does have a proper typescript story (built-in or not), I'll have to see how well it aligns with svelvet, or how it doesn't. That's TBD 🤷‍♂️ 

I've said this to a few people before, but it's possible that svelvet is *not* the right compiler for the project you're working on. You may benefit from the svelte-supported webpack/rollup bundlers, but I can't confirm whether svelte-preprocess+ts works better there or not 😅
